name:                klaraworks
version:             0.1.0.0
github:              "kirisaki/klaraworks"
license:             BSD3
author:              "Akihito KIRISAKI"
maintainer:          "kirisaki@klaraworks.net"
copyright:           "Copyright: (c) 2018 Akihito KIRISAKI"

extra-source-files:
- README.md
- ChangeLog.md
- client/index.html
- client/index.js
- client/Main.elm
- client/scss/style.scss

synopsis:            My website server
category:            Web

description:         Please see the README on GitHub at <https://github.com/kirisaki/klaraworks#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- directory
- http-types
- lens
- lens-aeson
- process
- template-haskell
- text
- vector
- wai
- warp
- yaml

library:
  source-dirs: server

executables:
  klaraworks:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - klaraworks

tests:
  klaraworks-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - klaraworks
